version: "3.1"
services:

 db:
    image: kiarro/dragon-base:1710
    # environment:
    #   POSTGRES_USER: dragon
    #   POSTGRES_PASSWORD: dragon
    #   POSTGRES_DB: dragon
    ports:
      - "1001:5432"

 my-payara-project:
    image: kiarro/dragon:1710
    ports:
      - "8080:8080"
      - "4848:4848"
      - "8181:8181"
      - "8000:8000"
    volumes:
      - ./depts/deployments:/opt/dept